# Generated by Django 5.0.6 on 2024-07-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='desciption',
            new_name='description',
        ),
    ]
